basic.forever(function () {
    pins.digitalWritePin(DigitalPin.P1, 1)
    led.plot(0, 4)
    basic.pause(100)
    pins.digitalWritePin(DigitalPin.P1, 0)
    led.unplot(0, 4)
    basic.pause(300)
    pins.digitalWritePin(DigitalPin.P1, 1)
    led.plot(1, 4)
    led.plot(1, 3)
    led.plot(0, 3)
    basic.pause(100)
    pins.digitalWritePin(DigitalPin.P1, 0)
    led.unplot(1, 4)
    led.unplot(1, 3)
    led.unplot(0, 3)
    basic.pause(300)
    pins.digitalWritePin(DigitalPin.P1, 1)
    led.plot(2, 4)
    led.plot(2, 3)
    led.plot(1, 2)
    led.plot(0, 2)
    basic.pause(100)
    pins.digitalWritePin(DigitalPin.P1, 0)
    led.unplot(2, 4)
    led.unplot(2, 3)
    led.unplot(1, 2)
    led.unplot(0, 2)
    basic.pause(300)
    pins.digitalWritePin(DigitalPin.P1, 1)
    led.plot(3, 4)
    led.plot(3, 3)
    led.plot(3, 2)
    led.plot(2, 1)
    led.plot(1, 1)
    led.plot(0, 1)
    basic.pause(100)
    pins.digitalWritePin(DigitalPin.P1, 0)
    led.unplot(3, 4)
    led.unplot(3, 2)
    led.unplot(3, 3)
    led.unplot(2, 1)
    led.unplot(1, 1)
    led.unplot(0, 1)
    basic.pause(300)
})
